version: "2"
services:
  api:
    container_name: light-app-api
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: light-app-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017